language: objective-c

rvm:
  - 2.1.7
  - 2.2.3

script:
  - cp script/ci/.gemrc ~/.gemrc
  - bundle update
  - bundle exec rake spec
  - rake install
  - luffa authorize

notifications:
  email: false
