language: objective-c

rvm:
  - 2.1.7
  - 2.2.3

script:
  - cp script/ci/.gemrc ~/.gemrc
  - bundle update
  - bundle exec rake spec
  - rake install
  - luffa authorize

notifications:
  email: false
  slack:
    rooms:
      secure: Uw8FBYmJjNZhLmEB/2T4VYfm2QrbCjErXiKS86J8VRt2pEC85cCC/ZGzgL+4l7gSOuRf1JpiFYqKMjTHO1kvLGRdDuCTZoOgq2KqXmiratV3jwwLqinBmQSA4aUMuqQTjBB15D80XkoXPVYYoH/kwiKjffMCpKvd6OIIdY2BrNU=
