language: objective-c

rvm:
  - 1.9.3
  - 2.1.5
  - 2.2.1

script:
  - cp script/ci/.gemrc ~/.gemrc
  - bundle update
  - bundle exec rake spec
  - rake install
  - luffa authorize

notifications:
  email: false
